/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student_package;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/**
 *
 * @author R. K. Gautam
 */
public class studentchangepassword extends javax.swing.JFrame {

    String roll;
    
    public studentchangepassword(String rollno) {
        initComponents();
        setSize(639, 496);
        setVisible(true);
        this.roll=rollno;
        
        jrollno.setText(roll);
        jrollno.setEnabled(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrollno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oldpass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        conpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT CHANGE PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 320, 50);

        jLabel2.setText("ROLL NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 110, 30);

        jrollno.setText("jLabel3");
        getContentPane().add(jrollno);
        jrollno.setBounds(190, 110, 410, 30);

        jLabel4.setText("OLD PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 180, 100, 30);

        jLabel5.setText("NEW PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 250, 90, 30);

        jLabel6.setText("CONFIRM PASSOWRD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 320, 130, 30);
        getContentPane().add(oldpass);
        oldpass.setBounds(190, 180, 370, 40);
        getContentPane().add(newpass);
        newpass.setBounds(190, 240, 370, 40);
        getContentPane().add(conpass);
        conpass.setBounds(190, 300, 370, 40);

        jButton1.setText("CHANGE PASSWORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 390, 190, 70);

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 390, 200, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            
            String oldpass=this.oldpass.getText();
            String newpass=this.newpass.getText();
            String confpass=conpass.getText();
        if(oldpass.equals("")||newpass.equals("")||confpass.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter all fields");
        }
        else if(!newpass.equals(confpass)){
            JOptionPane.showMessageDialog(rootPane, "Password do not match");
        }
        else{
        try {
            
            HttpResponse<String> httpResponse = Unirest.get("http://localhost:9595/studentchangepassword")
                    .queryString("rollno", roll)
                    .queryString("oldpass", oldpass)
                    .queryString("newpass", newpass)
                    .queryString("conpass", confpass)
                    .asString();

            String ans = httpResponse.getBody();
            System.out.println(ans);
            JOptionPane.showMessageDialog(rootPane, ans);

        } catch (Exception ex) {
            ex.printStackTrace();
        }    
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
      //          new studentchangepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jrollno;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField oldpass;
    // End of variables declaration//GEN-END:variables
}
