/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Teacher_Packages;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab-3_1
 */
public class facultychangepassword extends javax.swing.JFrame {
String username;
    /**
     * Creates new form facultychangepassword
     */
    public facultychangepassword(String username) {
        initComponents();
        setSize(619, 507);
        setVisible(true);
        this.username=username;
        tfuser.setText(username);
        tfuser.setEnabled(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfuser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jnew = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PASSWORD");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 260, 50);

        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 160, 40);

        tfuser.setText("jLabel3");
        getContentPane().add(tfuser);
        tfuser.setBounds(250, 70, 370, 40);

        jLabel4.setText("Old Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 130, 30);

        jLabel5.setText("New password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 230, 110, 50);

        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 320, 110, 30);

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 400, 200, 60);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 400, 190, 60);
        getContentPane().add(jnew);
        jnew.setBounds(250, 150, 210, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(250, 240, 210, 30);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(250, 320, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            
            String oldpass=jnew.getText();
            String newpass=jPasswordField2.getText();
            String confpass=jPasswordField3.getText();
        if(oldpass.equals("")||newpass.equals("")||confpass.equals("")){
            JOptionPane.showMessageDialog(rootPane,"Please enter all fields");
        }
        else if(!newpass.equals(confpass)){
            JOptionPane.showMessageDialog(rootPane, "Password doen't match");
        }
        else{
        try {
            
            HttpResponse<String> httpResponse = Unirest.get("http://localhost:9595/facultychangepassword")
                    .queryString("username", username)
                    .queryString("oldpass", oldpass)
                    .queryString("newpass", newpass)
                    .queryString("confpass", confpass)
                    .asString();

            String ans = httpResponse.getBody();
            System.out.println(ans);
            JOptionPane.showMessageDialog(rootPane, ans);

        } catch (Exception ex) {
            ex.printStackTrace();
        }    
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facultychangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facultychangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facultychangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facultychangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new facultychangepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jnew;
    private javax.swing.JLabel tfuser;
    // End of variables declaration//GEN-END:variables
}
