/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teacherstudent;

import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

/**
 *
 * @author Lab-3_1
 */
public class splashscreen extends javax.swing.JFrame {

    public splashscreen() throws IOException {
        setUndecorated(true);
        initComponents();
        setSize(623, 468);
        setLocationRelativeTo(null);
        lbphoto.setBounds(0, 0, getWidth(), getHeight());
        

        jprogress.setStringPainted(true);
        Image img = ImageIO.read(getClass().getResource("/pics/SEO_classMgmt_1130x448_R_tcm223-34570.png"));
        lbphoto.setIcon(new javax.swing.ImageIcon(img.getScaledInstance(lbphoto.getWidth(), lbphoto.getHeight(), Image.SCALE_SMOOTH)));
        setVisible(true);
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    try {
                        jprogress.setValue(i);
                        jprogress.setString("Loading..." + i + "%");
                        Thread.sleep(100);
                        if (i == 100) {

                            try {
                                new welcome_page().setVisible(true);
                            } catch (IOException ex) {
                                ex.printStackTrace();
                            }
                            dispose();

                        }
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
        ).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jprogress = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbphoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jprogress.setBackground(new java.awt.Color(240, 255, 255));
        jprogress.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jprogress);
        jprogress.setBounds(70, 400, 440, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("College Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 180, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Myanmar Text", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Teacher Student Companion");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 430, 70);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Government Polytecnic College");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 200, 330, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Developer :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 270, 150, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("R.K. Gautam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 260, 240, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome to College!!!!");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 340, 380, 40);

        lbphoto.setText("jLabel2");
        getContentPane().add(lbphoto);
        lbphoto.setBounds(10, 10, 260, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new splashscreen().setVisible(true);

                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jprogress;
    private javax.swing.JLabel lbphoto;
    // End of variables declaration//GEN-END:variables
}
